services:
  ecommerce-rabbit:
    image: rabbitmq:4.3.0-management
    container_name: ecommerce-rabbit
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq

volumes:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local